import {
  Armchair,
  ArrowUpDown,
  Building,
  Car,
  Cctv,
  Clapperboard,
  FireExtinguisher,
  Sofa,
  Sun,
  Tent,
  Video,
  Droplets,
  Dumbbell,
  Flower2,
  Footprints,
  Gamepad2,
  PartyPopper,
  Phone,
  PlugZap,
  ShieldCheck,
  ToyBrick,
  Trees,
  WavesLadder,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  pool: WavesLadder,
  clubhouse: Building,
  gym: Dumbbell,
  kids: ToyBrick,
  gardens: Trees,
  jogging: Footprints,
  yoga: Flower2,
  games: Gamepad2,
  party: PartyPopper,
  seating: Armchair,
  security: ShieldCheck,
  cctv: Cctv,
  intercom: Phone,
  power: Zap,
  parking: Car,
  lift: ArrowUpDown,
  ev: PlugZap,
  water: Droplets,
  theater: Clapperboard,
  gazebo: Tent,
  terrace: Sun,
  video: Video,
  fire: FireExtinguisher,
  sofa: Sofa,
};

export function AmenityIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Building;
  return <Icon aria-hidden className={className} strokeWidth={1.25} />;
}
